# Frontend Deployment Configuration for Render
services:
  - type: web
    name: addis-software-frontend
    env: static
    plan: starter
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_BACKEND_URL
        sync: false # Set this in Render dashboard for security
      - key: REACT_APP_SOCKET_URL
        sync: false # Set this in Render dashboard for security
      - key: GENERATE_SOURCEMAP
        value: false
      - key: NODE_VERSION
        value: 18
    # Custom headers for better performance and security
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
