services:
  - type: web
    name: addis-software-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false # Will be set manually in Render dashboard
      - key: FRONTEND_URL
        sync: false # Will be set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

databases:
  - name: addis-software-mongodb
    databaseName: addis_songs
    user: addis_user
    plan: starter
